# -*- coding: utf-8 -*-
"""
Generated UI code for Clip Multiple Layers dialog.
"""

from qgis.PyQt import QtCore, QtWidgets


class Ui_ClipMultipleLayers(object):
    def setupUi(self, ClipMultipleLayers):
        ClipMultipleLayers.setObjectName("ClipMultipleLayers")
        # ClipMultipleLayers.resize(524, 500)
        # ClipMultipleLayers.setMinimumSize(QtCore.QSize(524, 400))
        # ClipMultipleLayers.setMaximumSize(QtCore.QSize(2000, 2000))
        self.gridLayout = QtWidgets.QGridLayout(ClipMultipleLayers)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setRowStretch(3, 10)

        self.labelHeadline = QtWidgets.QLabel(ClipMultipleLayers)
        self.labelHeadline.setObjectName("labelHeadline")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHeadline.sizePolicy().hasHeightForWidth())
        self.labelHeadline.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.labelHeadline, 0, 0, 1, 1)

        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.labelMaskLayer = QtWidgets.QLabel(ClipMultipleLayers)
        self.labelMaskLayer.setObjectName("labelMaskLayer")
        sizePolicy.setHeightForWidth(self.labelMaskLayer.sizePolicy().hasHeightForWidth())
        self.labelMaskLayer.setSizePolicy(sizePolicy)
        self.horizontalLayout_1.addWidget(self.labelMaskLayer)
        self.comboBoxMaskLayer = QtWidgets.QComboBox(ClipMultipleLayers)
        self.comboBoxMaskLayer.setObjectName("comboBoxMaskLayer")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxMaskLayer.sizePolicy().hasHeightForWidth())
        self.comboBoxMaskLayer.setSizePolicy(sizePolicy)
        self.horizontalLayout_1.addWidget(self.comboBoxMaskLayer)
        self.gridLayout.addLayout(self.horizontalLayout_1, 1, 0, 1, 1)

        self.labelLayerSelection = QtWidgets.QLabel(ClipMultipleLayers)
        self.labelLayerSelection.setObjectName("labelLayerSelection")
        self.gridLayout.addWidget(self.labelLayerSelection, 2, 0, 1, 1)

        self.tableWidgetLayerSelection = QtWidgets.QTableWidget(ClipMultipleLayers)
        self.tableWidgetLayerSelection.setObjectName("tableWidgetLayerSelection")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        self.tableWidgetLayerSelection.setRowCount(0)
        self.tableWidgetLayerSelection.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetLayerSelection.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetLayerSelection.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.tableWidgetLayerSelection, 3, 0, 1, 1)

        self.labelVectorFormat = QtWidgets.QLabel(ClipMultipleLayers)
        self.labelVectorFormat.setObjectName("labelVectorFormat")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVectorFormat.sizePolicy().hasHeightForWidth())
        self.labelVectorFormat.setSizePolicy(sizePolicy)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_6.addWidget(self.labelVectorFormat)
        self.comboBoxVectorFormat = QtWidgets.QComboBox(ClipMultipleLayers)
        self.comboBoxVectorFormat.setObjectName("comboBoxVectorFormat")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxVectorFormat.sizePolicy().hasHeightForWidth())
        self.comboBoxVectorFormat.setSizePolicy(sizePolicy)
        self.horizontalLayout_6.addWidget(self.comboBoxVectorFormat)
        self.gridLayout.addLayout(self.horizontalLayout_6, 7, 0, 1, 1)

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkVector = QtWidgets.QCheckBox(ClipMultipleLayers)
        self.checkVector.setObjectName("checkVector")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkVector.sizePolicy().hasHeightForWidth())
        self.checkVector.setSizePolicy(sizePolicy)
        self.checkVector.setChecked(True)
        self.horizontalLayout_4.addWidget(self.checkVector)
        self.checkRaster = QtWidgets.QCheckBox(ClipMultipleLayers)
        self.checkRaster.setObjectName("checkRaster")
        self.checkRaster.setChecked(True)
        self.horizontalLayout_4.addWidget(self.checkRaster)
        self.gridLayout.addLayout(self.horizontalLayout_4, 8, 0, 1, 1)

        self.labelInstructions = QtWidgets.QLabel(ClipMultipleLayers)
        self.labelInstructions.setObjectName("labelInstructions")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.labelInstructions.sizePolicy().hasHeightForWidth())
        self.labelInstructions.setSizePolicy(sizePolicy)
        self.labelInstructions.setOpenExternalLinks(True)
        self.gridLayout.addWidget(self.labelInstructions, 10, 0, 1, 1)

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelOuputFolder = QtWidgets.QLabel(ClipMultipleLayers)
        self.labelOuputFolder.setObjectName("labelOuputFolder")
        self.horizontalLayout_2.addWidget(self.labelOuputFolder)
        self.lineEditOutputFolder = QtWidgets.QLineEdit(ClipMultipleLayers)
        self.lineEditOutputFolder.setObjectName("lineEditOutputFolder")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditOutputFolder.sizePolicy().hasHeightForWidth())
        self.lineEditOutputFolder.setSizePolicy(sizePolicy)
        self.lineEditOutputFolder.setReadOnly(True)
        self.horizontalLayout_2.addWidget(self.lineEditOutputFolder)
        self.pushButtonOutputFolder = QtWidgets.QPushButton(ClipMultipleLayers)
        self.pushButtonOutputFolder.setObjectName("pushButtonOutputFolder")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonOutputFolder.sizePolicy().hasHeightForWidth())
        self.pushButtonOutputFolder.setSizePolicy(sizePolicy)
        self.horizontalLayout_2.addWidget(self.pushButtonOutputFolder)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 0, 1, 1)

        self.labelSuggestions = QtWidgets.QLabel(ClipMultipleLayers)
        self.labelSuggestions.setObjectName("labelSuggestions")
        self.gridLayout.addWidget(self.labelSuggestions, 12, 0, 1, 1)

        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBoxLoadClippedLayers = QtWidgets.QCheckBox(ClipMultipleLayers)
        self.checkBoxLoadClippedLayers.setObjectName("checkBoxLoadClippedLayers")
        self.checkBoxLoadClippedLayers.setChecked(True)
        self.horizontalLayout_5.addWidget(self.checkBoxLoadClippedLayers)
        self.checkBoxSaveStyle = QtWidgets.QCheckBox(ClipMultipleLayers)
        self.checkBoxSaveStyle.setObjectName("checkBoxSaveStyle")
        self.horizontalLayout_5.addWidget(self.checkBoxSaveStyle)
        self.gridLayout.addLayout(self.horizontalLayout_5, 9, 0, 1, 1)

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(ClipMultipleLayers)
        self.label_5.setObjectName("label_5")
        self.label_5.setOpenExternalLinks(True)
        self.horizontalLayout_3.addWidget(self.label_5)
        self.button_box = QtWidgets.QDialogButtonBox(ClipMultipleLayers)
        self.button_box.setObjectName("button_box")
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.horizontalLayout_3.addWidget(self.button_box)
        self.button_box.accepted.connect(ClipMultipleLayers.accept)
        self.button_box.rejected.connect(ClipMultipleLayers.reject)
        self.gridLayout.addLayout(self.horizontalLayout_3, 14, 0, 1, 1)

        self.retranslateUi(ClipMultipleLayers)
        QtCore.QMetaObject.connectSlotsByName(ClipMultipleLayers)

    def retranslateUi(self, ClipMultipleLayers):
        _translate = QtCore.QCoreApplication.translate
        ClipMultipleLayers.setWindowTitle(_translate("ClipMultipleLayers", "ClipMultipleLayers"))
        self.labelHeadline.setText(_translate("ClipMultipleLayers", "Clip selected layers with the mask layer :"))
        self.labelMaskLayer.setText(_translate("ClipMultipleLayers", "Mask :"))
        self.labelLayerSelection.setText(_translate("ClipMultipleLayers", "Layers to clip : (default selection based on visibility in project)"))
        self.tableWidgetLayerSelection.horizontalHeaderItem(0).setText(_translate("ClipMultipleLayers", ""))
        self.tableWidgetLayerSelection.horizontalHeaderItem(1).setText(_translate("ClipMultipleLayers", "Layer"))
        self.labelVectorFormat.setText(_translate("ClipMultipleLayers", "Vector output format :"))
        self.checkVector.setText(_translate("ClipMultipleLayers", "Clip vector layers"))
        self.checkRaster.setText(_translate("ClipMultipleLayers", "Clip raster layers"))
        self.labelInstructions.setText(_translate("ClipMultipleLayers", "<html><head/><body><p>More instructions on the <a href=\"https://github.com/Taknok/Qgisplugin-ClipMultipleLayers/wiki\"><span style=\" text-decoration: underline; color:#0000ff;\">Github page</span></a>. Report issues <a href=\"https://github.com/Taknok/Qgisplugin-ClipMultipleLayers/issues\"><span style=\" text-decoration: underline; color:#0000ff;\">here</span></a>. </p><p>⚠️ Rasters clipping may freeze Qgis on small processors, <br/>Qgis will unfreez when the cut is finished.</p><p>Please fill and issue on Github or send an email before downvoting the plugin.</p></body></html>"))
        self.labelOuputFolder.setText(_translate("ClipMultipleLayers", "Output :"))
        self.pushButtonOutputFolder.setText(_translate("ClipMultipleLayers", "..."))
        self.labelSuggestions.setText(_translate("ClipMultipleLayers", "Suggestions ? Feedback ? -> pg.developper.fr@gmail.com"))
        self.checkBoxLoadClippedLayers.setText(_translate("ClipMultipleLayers", "Load clipped layers"))
        self.checkBoxSaveStyle.setText(_translate("ClipMultipleLayers", "Save vector styles (qml)"))
        self.label_5.setText(_translate("ClipMultipleLayers", "<html><head/><body><p>Please consider to rate the <a href=\"https://plugins.qgis.org/plugins/ClipMultipleLayers/\"><span style=\" text-decoration: underline; color:#0000ff;\">plugin</span></a> or <a href=\"https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=4DC3A78C398HW\"><span style=\" text-decoration: underline; color:#0000ff;\">support me</span></a>.</p></body></html>"))
